"""Protocol layer — message types, entity schemas, and message parsing."""

from protocol.messages import (
    RawMessage,
    SessionMetadata,
    FrameData,
)

from protocol.schema import (
    Vector2D,
    PlayerPosition,
    PlayerStats,
    PlayerHealth,
    PlayerInventory,
    ActiveItem,
    Enemy,
    Projectile,
    Laser,
    Projectiles,
    RoomInfo,
    GridEntity,
    Door,
    RoomLayout,
    Pickup,
    Bomb,
    FireHazard,
    Interactable,
    EventData,
    SensorMeta,
    DataMessage,
    SubscribeRequest,
    SubscribeAck,
    CommandResult,
)

__all__ = [
    "MessageType",
    "RawMessage",
    "SessionMetadata",
    "FrameData",
    "SensorMeta",
    "Vector2D",
    "PlayerPosition",
    "PlayerStats",
    "PlayerHealth",
    "PlayerInventory",
    "ActiveItem",
    "Enemy",
    "Projectile",
    "Laser",
    "Projectiles",
    "RoomInfo",
    "GridEntity",
    "Door",
    "RoomLayout",
    "Pickup",
    "Bomb",
    "FireHazard",
    "Interactable",
    "EventData",
    "SensorMeta",
    "DataMessage",
    "SubscribeRequest",
    "SubscribeAck",
    "CommandResult",
]
